[project]
name = "homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.9"
dependencies = [
    "pandas>=2.3.3",
    "pyarrow>=21.0.0",
    "scikit-learn==1.5.0",
    "seaborn>=0.13.2",
    "typer>=0.20.0",
]
